export CUBLAS_WORKSPACE_CONFIG=:4096:8

local_path='./results/coreset_mnist/test1'  # set your output path
dataset='mnist'
data_path=''  # default is: ../data
use_cuda=1
pool_size=10000
random_pool=0
init_size=0
coreset_size=200
ref_data='cand'
ref_epochs=125
ref_lr=1.5e-3
selection_steps=200
cur_train_steps=100
cur_train_lr=2e-2
eval_mode='none'
eval_steps=3
early_stop=3
only_new_data=1
class_balance=0
test_train_epochs=0
test_train_lr=5e-4
test_opt_type='adam'
test_train_batch_size=32
use_bn=0
save_checkpoint=1
slt_aug=1
seed=0


python3 -u data_summary.py --local_path=$local_path \
	--dataset=$dataset \
	--data_path=$data_path \
	--use_cuda=$use_cuda \
	--pool_size=$pool_size \
	--random_pool=$random_pool \
	--init_size=$init_size \
	--coreset_size=$coreset_size \
	--ref_data=$ref_data \
	--ref_epochs=$ref_epochs \
	--ref_lr=$ref_lr \
	--selection_steps=$selection_steps \
	--cur_train_steps=$cur_train_steps \
	--cur_train_lr=$cur_train_lr \
	--eval_mode=$eval_mode \
	--eval_steps=$eval_steps \
	--early_stop=$early_stop \
	--only_new_data=$only_new_data \
	--class_balance=$class_balance \
	--test_train_epochs=$test_train_epochs \
	--test_train_lr=$test_train_lr \
	--test_opt_type=$test_opt_type \
	--use_bn=$use_bn \
	--test_train_batch_size=$test_train_batch_size \
	--save_checkpoint=$save_checkpoint \
	--slt_aug=$slt_aug \
	--seed=$seed


batch_size=32
epochs=3000
lr=2e-2
weight_decay=0
opt_type='sgd'
repeat=1
drop_last=0
use_cuda=1
use_bn=0
last_n_acc=5
start_size=20
step_size=20
test_pool_loss=0


python3 -u test_procedure.py --local_path=$local_path \
	--dataset=$dataset \
	--batch_size=$batch_size \
	--epochs=$epochs \
	--lr=$lr \
	--weight_decay=$weight_decay \
	--opt_type=$opt_type \
	--repeat=$repeat \
	--drop_last=$drop_last \
	--use_cuda=$use_cuda \
	--use_bn=$use_bn \
	--last_n_acc=$last_n_acc \
	--start_size=$start_size \
	--step_size=$step_size \
	--test_pool_loss=$test_pool_loss \
	--seed=$seed
